FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# quiz app

Polls is a simple API allowing consumers to view polls and vote in them.

## Categories [/categories]

### List All Questions [GET]

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully loaded",
          "data": [
                    {
                        "id":1,
                        "name":"Literature",
                        "image":""
                    },
                    {
                        "id":1,
                        "name":"Science",
                        "image":""
                    },
                    {
                        "id":1,
                        "name":"Drama",
                        "image":""
                    },
                    {
                        "id":1,
                        "name":"Film",
                        "image":""
                    },
                    {
                        "id":1,
                        "name":"Art & Design",
                        "image":""
                    },
                    {
                        "id":1,
                        "name":"Sports",
                        "image":""
                    },
                    {
                        "id":1,
                        "name":"Languages",
                        "image":""
                    }
                ]
        }