FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# quiz app

Polls is a simple API allowing consumers to view polls and vote in them.

## Categories [/categories]

### List All Questions [GET]

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully loaded",
          "data": [
                    {
                        "topic_id":1,
                        "topic_name":"Literature",
                        "image_url":"https://i.ibb.co/fQYx1dH/dummy-profile.jpg",
                        "is_selected":0
                    },
                    {
                        "topic_id":2,
                        "topic_name":"Science",
                        "image_url":"https://i.ibb.co/fQYx1dH/dummy-profile.jpg",
                        "is_selected":1
                    },
                    {
                        "topic_id":4,
                        "topic_name":"Drama",
                        "image_url":"https://i.ibb.co/fQYx1dH/dummy-profile.jpg",
                        "is_selected":1
                    },
                    {
                        "topic_id":5,
                        "topic_name":"Film",
                        "image_url":"https://i.ibb.co/fQYx1dH/dummy-profile.jpg",
                        "is_selected":0
                    },
                    {
                        "topic_id":6,
                        "topic_name":"Art & Design",
                        "image_url":"https://i.ibb.co/fQYx1dH/dummy-profile.jpg",
                        "is_selected":0
                    },
                    {
                        "topic_id":7,
                        "topic_name":"Sports",
                        "image_url":"https://i.ibb.co/fQYx1dH/dummy-profile.jpg",
                        "is_selected":1
                    },
                    {
                        "topic_id":8,
                        "topic_name":"Languages",
                        "image_url":"https://i.ibb.co/fQYx1dH/dummy-profile.jpg",
                        "is_selected":0
                    }
                ]
        }
        
        
        
## Questions [/questions/{id}]

### List All Questions [GET]

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully loaded",
          "data": {
                    "question_code":1,
                    "questions":[
                    {
                        "question_type":1,
                        "question_number":1,
                        "question":"Question 1",
                        "question_desc":"",
                        "options":[
                                    "Option 1",
                                    "Option 2",
                                    "Option 3",
                                    "Option 4"
                        ],
                        "answer":"Option 1"
                    },
                    {
                        "question_type":1,
                        "question_number":2,
                        "question":"Question 2",
                        "question_desc":"",
                        "options":[
                                    "Option 1",
                                    "Option 2",
                                    "Option 3",
                                    "Option 4"
                        ],
                        "answer":"Option 2"
                    },
                    {
                        "question_type":1,
                        "question_number":3,
                        "question":"Question 3",
                        "question_desc":"",
                        "options":[
                                    "Option 1",
                                    "Option 2",
                                    "Option 3",
                                    "Option 4"
                        ],
                        "answer":"Option 3"
                    },
                    {
                        "question_type":1,
                        "question_number":4,
                        "question":"Question 4",
                        "question_desc":"",
                        "options":[
                                    "Option 1",
                                    "Option 2",
                                    "Option 3",
                                    "Option 4"
                        ],
                        "answer":"Option 4"
                    },
                    {
                        "question_type":1,
                        "question_number":5,
                        "question":"Question 5",
                        "question_desc":"",
                        "options":[
                                    "Option 1",
                                    "Option 2",
                                    "Option 3",
                                    "Option 4"
                        ],
                        "answer":"Option 3"
                    }]
                }
        }