FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# quiz app

Polls is a simple API allowing consumers to view polls and vote in them.

## Categories [/categories]

### List All Questions [GET]

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully loaded",
          "data": [
                    {
                        "topic_id":1,
                        "topic_name":"Literature",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":0
                    },
                    {
                        "topic_id":2,
                        "topic_name":"Science",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":1
                    },
                    {
                        "topic_id":4,
                        "topic_name":"Drama",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":1
                    },
                    {
                        "topic_id":5,
                        "topic_name":"Film",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":0
                    },
                    {
                        "topic_id":6,
                        "topic_name":"Art & Design",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":0
                    },
                    {
                        "topic_id":7,
                        "topic_name":"Sports",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":1
                    },
                    {
                        "topic_id":8,
                        "topic_name":"Languages",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":0
                    },
                    {
                        "topic_id":9,
                        "topic_name":"Literature",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":0
                    },
                    {
                        "topic_id":10,
                        "topic_name":"Science",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":1
                    },
                    {
                        "topic_id":11,
                        "topic_name":"Drama",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":1
                    },
                    {
                        "topic_id":12,
                        "topic_name":"Film",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":0
                    },
                    {
                        "topic_id":13,
                        "topic_name":"Art & Design",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":0
                    },
                    {
                        "topic_id":14,
                        "topic_name":"Sports",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":1
                    },
                    {
                        "topic_id":15,
                        "topic_name":"Languages",
                        "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                        "is_selected":0
                    }
                ]
        }
        
        
        
## Questions [/questions/{id}]

### List All Questions [GET]

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully loaded",
          "data": {
                    "question_code":1,
                    "questions":[
                    {
                        "question_type":1000,
                        "question_number":1,
                        "question":"How long is the first Harry Potter movie: Harry Potter and The Philosopher's Stone?",
                        "question_desc":"",
                        "options":[
                                    "1.5 hours",
                                    "2.5 hours",
                                    "3.5 hours",
                                    "4.5 hours"
                        ],
                        "answer":"Option 2"
                    },
                    {
                        "question_type":1001,
                        "question_number":2,
                        "question":"https://i.ibb.co/qMLmSSS/11.png",
                        "question_desc":"What is the name of this movie?",
                        "options":[
                                    "Diamon Necklace",
                                    "Banglore Days",
                                    "Amen",
                                    "Varathan"
                        ],
                        "answer":"Option 1"
                    },
                    {
                        "question_type":1003,
                        "question_number":3,
                        "question":"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
                        "question_desc":"What is Dorothy's surname in The Wizard of Oz?",
                        "options":[
                                    "Bale",
                                    "Gale",
                                    "Hale",
                                    "Yale"
                        ],
                        "answer":"Option 2"
                    },
                    {
                        "question_type":1002,
                        "question_number":4,
                        "question":"http://www.largesound.com/ashborytour/sound/brobob.mp3",
                        "question_desc":"Who plays a character named Lee Christmas in 'The Expendables' series of films?",
                        "options":[
                                    "Jason Statham",
                                    "Jet Li",
                                    "Sylvester Stallone",
                                    "Arnold Schwarzenegger"
                        ],
                        "answer":"Option 1"
                    },
                    {
                        "question_type":1000,
                        "question_number":5,
                        "question":"Who perfroms the most on-screen kills in the Lord of The Rings movies?",
                        "question_desc":"",
                        "options":[
                                    "Boromir",
                                    "Legolas",
                                    "Gimli",
                                    "Frodo"
                        ],
                        "answer":"Option 2"
                    }]
                }
        }
        
        
        
## Update Topics [/update_topics]

### List All Questions [POST]

+ Header (application/json)

        {
            "Authorization":"Bearer dasljhvlaskvaf"
        }

+ Request (application/json)

        [
            1,
            2,
            3
        ]

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully updated"
        }
        
        
 
## Submit Test [/submit_test]

### List All Questions [POST]

+ Request (application/json)

        {
            "question_code":"QT543",
            "user_id":1,
            "answers":[{"question_number":1,"answer":"Option 1"},{"question_number":2,"answer":"Option 2"},{"question_number":3,"answer":"Option 3"},{"question_number":4,"answer":"Option 4"}],
            "time":7890000,
            "time_used":376
        }

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully submitted"
        }
        
        
## Availbale Tests [/available_tests]

### List All Questions [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }
+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully listed",
          "data":[
                    {
                    "test_title":"Automobile test",
                    "test_id":34,
                    "topic_name":"vehicles",
                    "topic_id":26,
                    "image_url":"",
                    "instructions":"",
                    "number_questions":20,
                    "created_date":"20-03-2019",
                    "created_time":"02:30 pm"
                    },
                    {
                    "test_title":"Automobile test",
                    "test_id":35,
                    "topic_name":"vehicles",
                    "topic_id":26,
                    "image_url":"",
                    "instructions":"",
                    "number_questions":20,
                    "created_date":"20-03-2019",
                    "created_time":"02:30 pm"
                    },
                    {
                    "test_title":"Automobile test",
                    "test_id":36,
                    "topic_name":"vehicles",
                    "topic_id":26,
                    "image_url":"",
                    "instructions":"",
                    "number_questions":20,
                    "created_date":"20-03-2019",
                    "created_time":"02:30 pm"
                    }
                ]
        }
        
        
## Result of present Test [/test_result/{question_code}]

### List All Questions [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully listed",
          "data":{
                    "test_title":"automobile test",
                    "test_id":10,
                    "topic_name":"vehicle",
                    "topic_id":34,
                    "image_url":"",
                    "number_questions":20,
                    "number_correct":12,
                    "number_wrong":8,
                    "mark_scored":12,
                    "time_used":360,
                    "date_exam":"21-03-2019",
                    "time_exam":"02:30pm"
                }
        }
        
        
## Results [/results]

### List All Questions [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully listed",
          "data":{
                    [{
                    "test_title":"automobile test",
                    "test_id":10,
                    "result_id":28,
                    "topic_name":"vehicle", 
                    "topic_id":34,
                    "image_url":"",
                    "number_questions":20,
                    "number_correct":12,
                    "number_wrong":8,
                    "mark_scored":12,
                    "time_used":360,
                    "date_exam":"21-03-2019",
                    "time_exam":"02:30pm"
                    },
                    {"test_title":"automobile test",
                    "test_id":10,
                    "result_id":28,
                    "topic_name":"vehicle", 
                    "topic_id":34,
                    "image_url":"",
                    "number_questions":20,
                    "number_correct":12,
                    "number_wrong":8,
                    "mark_scored":12,
                    "time_used":360,
                    "date_exam":"21-03-2019",
                    "time_exam":"02:30pm"
                    },
                    {"test_title":"automobile test",
                    "test_id":10,
                    "result_id":28,
                    "topic_name":"vehicle", 
                    "topic_id":34,
                    "image_url":"",
                    "number_questions":20,
                    "number_correct":12,
                    "number_wrong":8,
                    "mark_scored":12,
                    "time_used":360,
                    "date_exam":"21-03-2019",
                    "time_exam":"02:30pm"
                    },
                    {"test_title":"automobile test",
                    "test_id":10,
                    "result_id":28,
                    "topic_name":"vehicle", 
                    "topic_id":34,
                    "image_url":"",
                    "number_questions":20,
                    "number_correct":12,
                    "number_wrong":8,
                    "mark_scored":12,
                    "time_used":360,
                    "date_exam":"21-03-2019",
                    "time_exam":"02:30pm"
                    },
                    {"test_title":"automobile test",
                    "test_id":10,
                    "result_id":28,
                    "topic_name":"vehicle", 
                    "topic_id":34,
                    "image_url":"",
                    "number_questions":20,
                    "number_correct":12,
                    "number_wrong":8,
                    "mark_scored":12,
                    "time_used":360,
                    "date_exam":"21-03-2019",
                    "time_exam":"02:30pm"
                    }]
                }
        }
        
        
## Home page [/home_page]

### List All Questions [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully listed",
          "data":{
                "name":"Sithara Krishnakumar",
                "image_url":"https://i.ibb.co/kmrbPJp/22687832-1426096807440196-4276502542564884957-n.jpg",
                "achieved_score":24,
                "total_score":30,
                "result":[{"correct_anwers":8,"total_questions":12,"score":14},
                {"correct_anwers":8,"total_questions":12,"score":14},
                {"correct_anwers":8,"total_questions":12,"score":14}],
                "subscribed_topics":["vehicle", "internet"]}
                }
        }
        
        
## Notification page [/notifications]

### List All Questions [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "message": "Notification listed successfully",
            "data": [
                        {
                            "id":1,
                            "title":"Notification 1",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/VwCS3H4/joseph.jpg",
                            "time":"now"
                        },
                        {
                            "id":2,
                            "title":"Notification 2",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/kMD8crK/spirit.jpg",
                            "time":"30 minutes ago"
                        },
                        {
                            "id":3,
                            "title":"Notification 3",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/860nkxz/pretham.jpg",
                            "time":"1 day ago"
                        },
                        {
                            "id":4,
                            "title":"Notification 4",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/kMD8crK/spirit.jpg",
                            "time":"1 day ago"
                        },
                        {
                            "id":5,
                            "title":"Notification 5",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/860nkxz/pretham.jpg",
                            "time":"1 day ago"
                        },
                        {
                            "id":6,
                            "title":"Notification 6",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/VwCS3H4/joseph.jpg",
                            "time":"1 day ago"
                        },
                        {
                            "id":7,
                            "title":"Notification 7",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/kMD8crK/spirit.jpg",
                            "time":"1 day ago"
                        },
                        {
                            "id":8,
                            "title":"Notification 8",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/860nkxz/pretham.jpg",
                            "time":"1 day ago"
                        },
                        {
                            "id":9,
                            "title":"Notification 9",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/VwCS3H4/joseph.jpg",
                            "time":"2 day ago"
                        },
                        {
                            "id":10,
                            "title":"Notification 10",
                            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            "image":"https://i.ibb.co/kMD8crK/spirit.jpg",
                            "time":"2 day ago"
                        }
                    ]
        }
        
        
        
## Test Under Topic [/topic_tests/{topic_id}]

### List All Questions [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }

+ Response 200 (application/json)

        {
          "status":"success",
          "message":"successfully listed",
          "data":[
                    {
                    "test_title":"Automobile test",
                    "test_id":34,
                    "topic_name":"vehicles",
                    "topic_id":26,
                    "image_url":"",
                    "instructions":"",
                    "number_questions":20,
                    "created_date":"20-03-2019",
                    "created_time":"02:30 pm"
                    },
                    {
                    "test_title":"Automobile test",
                    "test_id":35,
                    "topic_name":"vehicles",
                    "topic_id":26,
                    "image_url":"",
                    "instructions":"",
                    "number_questions":20,
                    "created_date":"20-03-2019",
                    "created_time":"02:30 pm"
                    },
                    {
                    "test_title":"Automobile test",
                    "test_id":36,
                    "topic_name":"vehicles",
                    "topic_id":26,
                    "image_url":"",
                    "instructions":"",
                    "number_questions":20,
                    "created_date":"20-03-2019",
                    "created_time":"02:30 pm"
                    }
                ]
        }
        
        
        
        
## Topic Details [/topic_details/{topic_id}]

### List All Questions [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }

+ Response 200 (application/json)

        {
            "status":"success",
            "message":"successfully listed",
            "data":
                    {
                    "topic_name":"vehicle",
                    "image_url":"https://i.ibb.co/d039qKf/innovation.png",
                    "number_followers":300,
                    "number_tests":100,
                    "matches_played":20,
                    "topic_desc":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambledit to make a type specimen book.",
                    "is_active": 0
                }
        }
        
        
        
        
## Follow Topic [/follow_topic/{topic_id}]

### List All Questions [GET]

+ Header (application/json)

        {
            "Authorization":"Bearer caksjcahksjascdasca"
        }

+ Response 200 (application/json)

        {
            "status":"success",
            "message":"topic followed"
        }
        
        
        
        
## Login [/login]

### Login [POST]

+ Request (application/json)

        {
            "email": "xxx@yyy.com",
            "password": "password"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "user successfully logged in",
            "data": {
                        "token": "elxkjkjskjzvkjhkjkjjhckjhkjkzjhkjbkjbkjszcv"
            }
        
        }
        
## Token Refresh [/token_refresh]

### Login [POST]

+ Request (application/json)

        {
            "token": "elxkjkjskjzvkjhkjkjjhckjhkjkzjhkjbkjbkjszcv"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "token successfully refreshed",
            "data": {
                        "token": "fbdbedzsdzdgnsdgnsdfgsrtjn"
            }
        
        }
        
        
## Register [/register]

### Register [POST]

+ Request (application/json)

        {
            "name": "abcd",
            "email": "abcd@efg.com",
            "password": "password",
            "phone": "9037324059",
            "gender": "Male"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "account successfully created",
        
        }
        
        
## Edit Profile [/edit_profile]

### Register [POST]

+ Request (application/json)

        {
            "name": "abcd",
            "email": "abcd@efg.com",
            "password": "password",
            "phone": "9037324059",
            "gender": "Male"
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "profile updated successfully"
        
        }
        

## Forgot Password [/reset_password]

### Register [POST]

+ Request (application/json)

        {
            "phone": "9037324058",
        }
        
+ Response 200 (application/json)

        {
            "status": "success",
            "message": "OTP sent to phone",
            "data":"1234"
        
        }